[WIP] Refactor ECH status tracking
Waiting for the client alert to detect GREASE on the server side is
fragile, the network connection could have been reset before. The server
should therefore check the SNI from the outer Client Hello for the
expected name and infer GREASE usage from that.

This patch tries to:

 - Make GREASE an alias for rejection.
 - Change "offered" to true even in case of GREASE.

I also started trying to separate client and server events, but the
current patch is incomplete in that regard.

This patch is incomplete and has some test failures:

    ../bin/go test ./crypto/tls
    still stuck in echStatusAdvertised - was there a TLS error?
    still stuck in echStatusAdvertised - was there a TLS error?
    still stuck in echStatusAdvertised - was there a TLS error?
    --- FAIL: TestECHHandshake (0.03s)
        --- FAIL: TestECHHandshake/02 (0.00s)
            ech_test.go:748: success / bypassed: grease
            ech_test.go:809: client and server disagree on ech usage
            ech_test.go:810: client={clientDone:true serverDone:false clientStatus:3 serverStatus:0 connState:{Version:772 HandshakeComplete:true DidResume:false CipherSuite:4867 NegotiatedProtocol: NegotiatedProtocolIsMutual:true ServerName:example.com PeerCertificates:[0xc00044e680] VerifiedChains:[[0xc00044e680 0xc00044db80]] VerifiedDC:false SignedCertificateTimestamps:[] OCSPResponse:[] TLSUnique:[] ECHAccepted:false ECHOffered:false CFControl:<nil> ekm:0x12ce7e0} err:<nil>}
            ech_test.go:811: server={clientDone:true serverDone:false clientStatus:2 serverStatus:3 connState:{Version:772 HandshakeComplete:true DidResume:false CipherSuite:4867 NegotiatedProtocol: NegotiatedProtocolIsMutual:true ServerName:example.com PeerCertificates:[] VerifiedChains:[] VerifiedDC:false SignedCertificateTimestamps:[] OCSPResponse:[] TLSUnique:[] ECHAccepted:false ECHOffered:true CFControl:<nil> ekm:0x12ce7e0} err:<nil>}
        --- FAIL: TestECHHandshake/03 (0.00s)
            ech_test.go:748: success / bypassed: client invalid version
            ech_test.go:773: got offered=true; want false
            ech_test.go:777: got grease=false; want true
            ech_test.go:793: got rejected=true; want false
            ech_test.go:809: client and server disagree on ech usage
            ech_test.go:810: client={clientDone:true serverDone:false clientStatus:3 serverStatus:0 connState:{Version:771 HandshakeComplete:true DidResume:false CipherSuite:52393 NegotiatedProtocol: NegotiatedProtocolIsMutual:true ServerName:example.com PeerCertificates:[0xc00044e680] VerifiedChains:[[0xc00044e680 0xc00044db80]] VerifiedDC:false SignedCertificateTimestamps:[] OCSPResponse:[] TLSUnique:[174 213 239 164 215 62 195 120 26 98 135 225] ECHAccepted:false ECHOffered:false CFControl:<nil> ekm:0x12d05a0} err:<nil>}
            ech_test.go:811: server={clientDone:true serverDone:false clientStatus:2 serverStatus:3 connState:{Version:771 HandshakeComplete:true DidResume:false CipherSuite:52393 NegotiatedProtocol: NegotiatedProtocolIsMutual:true ServerName:example.com PeerCertificates:[] VerifiedChains:[] VerifiedDC:false SignedCertificateTimestamps:[] OCSPResponse:[] TLSUnique:[174 213 239 164 215 62 195 120 26 98 135 225] ECHAccepted:false ECHOffered:true CFControl:<nil> ekm:0x12d05a0} err:<nil>}
        --- FAIL: TestECHHandshake/09 (0.00s)
            ech_test.go:748: success / bypassed: client-facing invalid version
            ech_test.go:781: got clientBypassed=true; want false
            ech_test.go:785: got serverBypassed=false; want true
            ech_test.go:809: client and server disagree on ech usage
            ech_test.go:810: client={clientDone:false serverDone:false clientStatus:0 serverStatus:0 connState:{Version:771 HandshakeComplete:true DidResume:false CipherSuite:52393 NegotiatedProtocol: NegotiatedProtocolIsMutual:true ServerName:cloudflare-esni.com PeerCertificates:[0xc000480000] VerifiedChains:[[0xc000480000 0xc00044db80]] VerifiedDC:false SignedCertificateTimestamps:[] OCSPResponse:[] TLSUnique:[117 84 123 171 99 3 247 151 200 210 1 51] ECHAccepted:false ECHOffered:true CFControl:<nil> ekm:0x12d05a0} err:<nil>}
            ech_test.go:811: server={clientDone:true serverDone:false clientStatus:1 serverStatus:0 connState:{Version:771 HandshakeComplete:true DidResume:false CipherSuite:52393 NegotiatedProtocol: NegotiatedProtocolIsMutual:true ServerName:cloudflare-esni.com PeerCertificates:[] VerifiedChains:[] VerifiedDC:false SignedCertificateTimestamps:[] OCSPResponse:[] TLSUnique:[117 84 123 171 99 3 247 151 200 210 1 51] ECHAccepted:false ECHOffered:false CFControl:<nil> ekm:0x12d05a0} err:<nil>}
        --- FAIL: TestECHHandshake/12 (0.01s)
            ech_test.go:748: hrr / bypassed: grease
            ech_test.go:773: got offered=true; want false
            ech_test.go:777: got grease=false; want true
            ech_test.go:793: got rejected=true; want false
            ech_test.go:809: client and server disagree on ech usage
            ech_test.go:810: client={clientDone:true serverDone:false clientStatus:3 serverStatus:0 connState:{Version:772 HandshakeComplete:true DidResume:false CipherSuite:4867 NegotiatedProtocol: NegotiatedProtocolIsMutual:true ServerName:example.com PeerCertificates:[0xc00044c000] VerifiedChains:[[0xc00044c000 0xc00044db80]] VerifiedDC:false SignedCertificateTimestamps:[] OCSPResponse:[] TLSUnique:[] ECHAccepted:false ECHOffered:false CFControl:<nil> ekm:0x12ce7e0} err:<nil>}
            ech_test.go:811: server={clientDone:true serverDone:false clientStatus:2 serverStatus:3 connState:{Version:772 HandshakeComplete:true DidResume:false CipherSuite:4867 NegotiatedProtocol: NegotiatedProtocolIsMutual:true ServerName:example.com PeerCertificates:[] VerifiedChains:[] VerifiedDC:false SignedCertificateTimestamps:[] OCSPResponse:[] TLSUnique:[] ECHAccepted:false ECHOffered:true CFControl:<nil> ekm:0x12ce7e0} err:<nil>}
    FAIL
    FAIL	crypto/tls	1.891s
    FAIL